'use strict';
/* One shared lesson, each card assigned to both players. No secret keys in this file. */
const DuoPlan={
 quiz(cards,order){return order.flatMap((card,i)=>[{card,role:'host'},{card,role:'guest'}]);},
 options(card,task){const a=[...card.options];const n=task%a.length;return a.slice(n).concat(a.slice(0,n));},
 target(subject,card){return subject.id==='arabic'||subject.id==='english'?card.word:subject.id==='math'?card.front:card.word;}
};
const Duo=(()=>{
 const CFG='roqaya_firebase_v2', AUTH='roqaya_auth_v2', LAST='roqaya_room_v3';
 let cfg=null,auth=null,room=null,id='',role='host',local=false,timer=null,active=false,epoch=0,view='',busy=false,online=true,drawRefresh=null,flushing=false;
 let pending={},pendingPath='',canvasStrokes={},stroke=null,ink='#7753c7',renderedPhase='';
 const names={host:'إِيسُو',guest:'رُقَيَّة'};
 try{cfg=JSON.parse(localStorage.getItem(CFG));auth=JSON.parse(localStorage.getItem(AUTH));}catch(e){}
 if(!configValid(cfg))cfg=window.SCHOOL_CONFIG||null;
 let invitation='',lastSignal='',lastHeartbeat=0,finishedRev=0;
 const webBase=()=>{try{const u=new URL(cfg?.webURL||window.location.href);return u.protocol==='https:'&&u.hostname!=='roqaya.local'&&!u.username&&!u.password?u.origin+u.pathname:'';}catch(e){return '';}};
 function configValid(c){try{const u=new URL(c.databaseURL);return /^[A-Za-z0-9_-]{20,}$/.test(c.apiKey)&&u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&/^\/[\/]?$/.test(u.pathname)&&/^[a-z0-9-]+\.(firebaseio\.com|[a-z0-9-]+\.firebasedatabase\.app)$/.test(u.hostname);}catch(e){return false;}}
 function readInput(label,type='text'){const wrap=el('label',label,'field'),input=el('input');input.type=type;input.autocomplete='off';input.spellcheck=false;input.dir='ltr';wrap.append(input);return [wrap,input];}
 function status(text){const e=document.getElementById('duo-status');if(e)e.textContent=text;}
 async function jsonFetch(url,options={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{...options,signal:controller.signal});if(!r.ok)throw Error(r.status===401||r.status===403?'تَعَذَّرَ الدُّخُولُ. رَاجِعْ إِعْدَادَاتِ الْخِدْمَةِ وَصَلَاحِيَّةَ الْجَلْسَةِ.':'تَعَذَّرَ الِاتِّصَالُ. حَاوِلْ مَرَّةً أُخْرَى.');return await r.json();}finally{clearTimeout(timeout);}}
 async function token(){
  if(auth&&auth.project===cfg.apiKey&&auth.expiry>Date.now()+60000)return auth.token;
  if(auth&&auth.project===cfg.apiKey&&auth.refresh){const d=await jsonFetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(cfg.apiKey),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=refresh_token&refresh_token='+encodeURIComponent(auth.refresh)});auth={project:cfg.apiKey,uid:d.user_id,token:d.id_token,refresh:d.refresh_token,expiry:Date.now()+Number(d.expires_in)*1000};}
  else{const d=await jsonFetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(cfg.apiKey),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});auth={project:cfg.apiKey,uid:d.localId,token:d.idToken,refresh:d.refreshToken,expiry:Date.now()+Number(d.expiresIn)*1000};}
  localStorage.setItem(AUTH,JSON.stringify(auth));return auth.token;
 }
 async function db(path,method='GET',data){const t=await token();return jsonFetch(cfg.databaseURL.replace(/\/$/,'')+'/studyRoomsV3/'+id+(path?'/'+path:'')+'.json?auth='+encodeURIComponent(t),{method,headers:{'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});}
 function stop(){active=false;epoch++;clearTimeout(timer);timer=null;drawRefresh=null;view='';pending={};stroke=null;}
 function leave(){if(active&&!confirm('هَلْ تُرِيدُ مُغَادَرَةَ الْجَلْسَةِ؟'))return;invitation='';stop();home();}
 function lobby(){stop();reset('duo');title('مَدْرَسَةُ رُقَيَّة 💜','إِيسُو وَرُقَيَّة • نَتَعَلَّمُ مَعًا مِنَ الْبِدَايَةِ إِلَى النِّهَايَةِ.');
  const hero=el('div',null,'hero center');add(hero,el('div','👨‍👧','big'),el('h2',invitation?'إِيسُو يَنْتَظِرُكِ!':'مَوْعِدُنَا لِنَتَعَلَّمَ مَعًا'),el('p','غُرْفَةٌ وَاحِدَةٌ، وَالدَّرْسُ نَفْسُهُ عَلَى الْجِهَازَيْنِ.'));root.append(hero);
  const panel=el('section',null,'panel');
  if(configValid(cfg)){
   if(!invitation)panel.append(button('👨 إِيسُو: أَنْشِئْ غُرْفَةَ الْمُذَاكَرَةِ',createRoom,'primary room-create'));
   const [w,input]=readInput('رَابِطُ الدَّعْوَةِ أَوْ رَمْزُ الْغُرْفَةِ');input.value=invitation;input.placeholder='الصقي دعوة إيسو هنا';add(panel,w,button('👧 رُقَيَّة: ادْخُلِي مَعَ إِيسُو',()=>joinRoom(extractInvite(input.value)),'primary room-join'));
   if(invitation&&!window.Android){const link=el('a','فَتْحُ الدَّعْوَةِ فِي تَطْبِيقِ أَنْدْرُويد','app-open');link.href='roqayaschool://join?room='+invitation;panel.append(link);}
   const last=localStorage.getItem(LAST);if(last)panel.append(button('الْعَوْدَةُ إِلَى غُرْفَتِنَا',()=>resume(last),'secondary'));
  }else panel.append(el('p','يُكْمِلُ إِيسُو إِعْدَادَ التَّطْبِيقِ أَوَّلًا.'));
  const msg=el('p','','muted');msg.id='duo-status';add(root,panel,msg,button('⚙️ إِعْدَادَاتُ وَلِيِّ الْأَمْرِ',settings,'tiny'));
 }
 function validRoomCode(code){return /^([0-9]{6}|[a-f0-9]{32})$/i.test(code||'');}
 function normalizeRoomCode(value){return String(value||'').replace(/[٠-٩]/g,n=>String(n.charCodeAt(0)-1632)).replace(/[۰-۹]/g,n=>String(n.charCodeAt(0)-1776)).replace(/\s/g,'').toLowerCase();}
 function extractInvite(value){const text=String(value).trim(),code=normalizeRoomCode(text);if(validRoomCode(code))return code;try{const u=new URL(text),room=normalizeRoomCode(new URLSearchParams(u.hash.slice(1)).get('room')||u.searchParams.get('room'));return validRoomCode(room)?room:'';}catch(e){return '';}}
 function acceptInvite(value){const code=extractInvite(value);if(!code)return;if(active&&id===code)return;if(active&&!confirm('هَلْ نَفْتَحُ الدَّعْوَةَ الْجَدِيدَةَ؟'))return;invitation=code;lobby();}
 async function shareInvite(){const base=webBase();if(!base){status('يَلْزَمُ إِضَافَةُ رَابِطِ نُسْخَةِ الْوِيبِ مَرَّةً وَاحِدَةً مِنْ إِعْدَادَاتِ وَلِيِّ الْأَمْرِ.');return;}const link=base+'#room='+id;const text='يَا رُقَيَّة، تَعَالَيْ نَتَعَلَّمْ مَعًا 💜\n'+link;
  if(window.Android?.share){Android.share(text);return;}
  if(navigator.share){try{await navigator.share({title:'دعوة إيسو للمذاكرة',text:'يَا رُقَيَّة، تَعَالَيْ نَتَعَلَّمْ مَعًا 💜',url:link});return;}catch(e){if(e.name==='AbortError')return;}}
  try{await navigator.clipboard.writeText(link);status('نُسِخَ رَابِطُ الدَّعْوَةِ. أَرْسِلْهُ لِرُقَيَّة.');}catch(e){const box=el('textarea');box.value=link;box.readOnly=true;root.append(box);box.focus();box.select();status('حَدِّدِ الرَّابِطَ وَانْسَخْهُ.');}
 }
 function settings(){reset('duo');title('إِعْدَادَاتُ وَلِيِّ الْأَمْرِ','تُضْبَطُ مَرَّةً وَاحِدَةً قَبْلَ أَوَّلِ جَلْسَةٍ.');const [w1,k]=readInput('Web API Key'),[w2,u]=readInput('Realtime Database URL'),[w3,web]=readInput('رابط نسخة التطبيق على الويب — لدعوة رقية');k.value=cfg?.apiKey||'';u.value=cfg?.databaseURL||'';web.value=cfg?.webURL||webBase();add(root,w3,el('p','اِنْشُرْ مِلَفَّاتِ web وَأَضِفْ قَوَاعِدَ studyRoomsV3 مَرَّةً وَاحِدَةً. إِعْدَادَاتُ الْمَشْرُوعِ الْعَامَّةُ مَوْجُودَةٌ بِالْفِعْلِ.','muted'),w1,w2,button('حِفْظٌ',()=>{const c={apiKey:k.value.trim(),databaseURL:u.value.trim().replace(/\/$/,''),webURL:web.value.trim()};if(!configValid(c)){alert('تَأَكَّدْ مِنْ بَيَانَاتِ الْخِدْمَةِ.');return;}if(c.webURL){try{const x=new URL(c.webURL);if(x.protocol!=='https:'||x.hostname==='roqaya.local'||x.username||x.password||x.hash||x.search)throw Error();}catch(e){alert('أَدْخِلْ رَابِطَ HTTPS لِنُسْخَةِ التَّطْبِيقِ، دُونَ رَمْزِ غُرْفَةٍ.');return;}}if(cfg?.apiKey!==c.apiKey||cfg?.databaseURL!==c.databaseURL){auth=null;localStorage.removeItem(AUTH);localStorage.removeItem(LAST);}cfg=c;localStorage.setItem(CFG,JSON.stringify(c));lobby();},'primary'),button('رُجُوعٌ',lobby));backupPanel();}
 function backupPanel(){const box=el('textarea');box.value=JSON.stringify(state);box.setAttribute('aria-label','نسخة التقدم');add(root,el('h3','نُسْخَةُ التَّقَدُّمِ الْمَحْفُوظَةِ'),box,button('تَحْدِيدٌ لِلنَّسْخِ',()=>{box.focus();box.select();}),button('اِسْتِعَادَةٌ',()=>{try{const x=JSON.parse(box.value),ids=SUBJECTS.flatMap(s=>s.lessons.map(l=>l.id));if(!valid(x)||Object.keys(x.best).some(k=>!ids.includes(k)||x.best[k]>3)||Object.keys(x.seen).some(k=>!ids.includes(k)))throw Error();if(confirm('هَلْ نَسْتَعِيدُ هَذِهِ النَّتَائِجَ؟')){state=x;save();settings();}}catch(e){alert('نُسْخَةٌ غَيْرُ صَالِحَةٍ.');}}));}
 function initial(){return {phase:'waiting',rev:1,round:0,activeRole:'host',progress:{}};}
 function sixDigits(){const b=new Uint32Array(1),limit=0x100000000-(0x100000000%900000);do{crypto.getRandomValues(b);}while(b[0]>=limit);return String(100000+(b[0]%900000));}
 async function reserveRoom(){const t=await token(),url=cfg.databaseURL.replace(/\/$/,'')+'/studyRoomsV3/'+id+'.json?auth='+encodeURIComponent(t),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{method:'PUT',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(room)});if(r.status===403)return false;if(!r.ok)throw Error('تَعَذَّرَ إِنْشَاءُ الْغُرْفَةِ (رمز '+r.status+').');return true;}finally{clearTimeout(timeout);}}
 async function createRoom(){if(busy)return;busy=true;status('جَارٍ إِنْشَاءُ الْجَلْسَةِ…');try{local=false;await token();role='host';room={hostUid:auth.uid,createdAt:{'.sv':'timestamp'},expiresAt:Date.now()+2*60*60*1000,control:initial(),presence:{host:{'.sv':'timestamp'}}};let created=false;for(let attempt=0;attempt<8&&!created;attempt++){id=sixDigits();created=await reserveRoom();}if(!created)throw Error('رَفَضَتْ Firebase إِنْشَاءَ الْغُرْفَةِ. تَأَكَّدْ أَنَّ قَوَاعِدَ الْأَرْقَامِ السِّتَّةِ مَنْشُورَةٌ.');localStorage.setItem(LAST,id);activate();}catch(e){status(e.message||'تَعَذَّرَ إِنْشَاءُ الْغُرْفَةِ.');}finally{busy=false;}}
 async function joinRoom(code){if(busy)return;id=normalizeRoomCode(code);if(!validRoomCode(id)){status('الرَّمْزُ غَيْرُ صَحِيحٍ. أَدْخِلْ سِتَّةَ أَرْقَامٍ أَوِ اسْتَخْدِمْ رَابِطَ الدَّعْوَةِ.');return;}busy=true;status('جَارٍ الِانْضِمَامُ…');try{local=false;await token();await db('guestUid','PUT',auth.uid);role='guest';room=await db('');if(room.hostUid===auth.uid)role='host';localStorage.setItem(LAST,id);activate();}catch(e){status(e.message);}finally{busy=false;}}
 async function resume(code){if(busy)return;busy=true;try{local=false;id=code;await token();room=await db('');if(!room)throw Error('انْتَهَتِ الْجَلْسَةُ. أَنْشِئْ جَلْسَةً جَدِيدَةً.');role=room.hostUid===auth.uid?'host':'guest';activate();}catch(e){status(e.message);}finally{busy=false;}}
 function activate(){invitation='';lastSignal='';lastHeartbeat=0;finishedRev=0;active=true;online=true;view='';epoch++;render();poll(epoch);}
 async function poll(e){if(!active||local||e!==epoch)return;try{const [ctl,guest,flags,signals,presence]=await Promise.all([db('control'),db('guestUid'),db('flags'),db('signals'),db('presence')]);if(e!==epoch||!active)return;let r=ctl?{...room,control:ctl,guestUid:guest,flags,signals,presence}:null;if(ctl&&['quiz','write'].includes(ctl.phase)){const response=await db('responses/r'+ctl.rev);r.responses={['r'+ctl.rev]:response||(ctl.rev===room.control.rev?room.responses?.['r'+ctl.rev]:null)};if(ctl.phase==='write')r.boards={['r'+ctl.rev]:await db('boards/r'+ctl.rev)};}if(e!==epoch||!active)return;if(!r){stop();lobby();status('انْتَهَتِ الْجَلْسَةُ.');return;}if(!room||r.control.rev>=room.control.rev)room=r;online=true;if(Date.now()-lastHeartbeat>10000){await db('presence/'+role,'PUT',{'.sv':'timestamp'});lastHeartbeat=Date.now();}render();updateSession();if(host()&&room.guestUid&&room.control.phase==='waiting')await control({phase:'pick'});}catch(err){if(e!==epoch)return;online=false;status('🟠 انْقَطَعَ الِاتِّصَالُ. نُعِيدُ الْمُحَاوَلَةَ…');sessionOverlay();}if(active&&e===epoch)timer=setTimeout(()=>poll(e),1000);}
 function host(){return local||role==='host';}
 function mine(r){return !room?.flags?.paused&&(local||r===role);}
 function lesson(){const c=room.control,s=SUBJECTS.find(x=>x.id===c.subject);return {s,l:s?.lessons.find(x=>x.id===c.lesson)};}
 function task(){const {l}=lesson(),c=room.control;return DuoPlan.quiz(l.cards,c.order)[c.round];}
 function response(){return room.responses?.['r'+room.control.rev]||null;}
 function putLocal(path,value){const a=path.split('/');let o=room;for(let i=0;i<a.length-1;i++)o=o[a[i]]||(o[a[i]]={});o[a.at(-1)]=value;}
 async function write(path,value){if(!active)return false;if(!local&&!online){status('انْتَظِرْ عَوْدَةَ الِاتِّصَالِ.');return false;}const e=epoch;try{if(!local)await db(path,'PUT',value);if(e!==epoch||!active)return false;putLocal(path,value);return true;}catch(e){online=false;status('لَمْ يُحْفَظِ التَّغْيِيرُ. حَاوِلْ بَعْدَ عَوْدَةِ الِاتِّصَالِ.');return false;}}
 async function control(patch){if(!host()||busy||room.flags?.paused||(!local&&!room.guestUid&&patch.phase!=='waiting'))return;if(room.control.phase==='write'){await flush();if(flushing||Object.keys(pending).length){status('انْتَظِرْ حَفْظَ الْخُطُوطِ قَبْلَ الِانْتِقَالِ.');return;}}busy=true;const c={...room.control,...patch,rev:room.control.rev+1};c.activeRole=c.round%2?'guest':'host';if(await write('control',c)){view='';render();}busy=false;}
 function shell(){reset('duo');drawRefresh=null;const top=el('div',null,'duo-top');add(top,el('strong','مَدْرَسَةُ رُقَيَّة 💜'),button('مُغَادَرَةٌ',leave));root.append(top);const msg=el('p','','muted');msg.id='duo-status';root.append(msg);
  const row=el('div',null,'session-tools');if(host()){
   if(!local)row.append(button('💌 دَعْوَةُ رُقَيَّة',shareInvite));
   if(room.guestUid||local)add(row,button('🏡 الْمَوَادُّ',schoolHome),button('⭐ إِنْجَازَاتُنَا',()=>control({phase:'rewards'})),button('☕ اِسْتِرَاحَةٌ',()=>pause(true)));
  }else add(row,button('💜 أَحْسَنْتَ يَا إِيسُو',()=>signal('heart')));
  root.append(row);const note=el('p','','session-note');note.id='session-note';note.setAttribute('aria-live','polite');root.append(note);
  if(host()&&!local)root.append(button('إِنْهَاءُ الْجَلْسَةِ وَحَذْفُهَا',async()=>{if(!confirm('هَلْ نُنْهِي الْجَلْسَةَ وَنَحْذِفُ بَيَانَاتِهَا؟'))return;try{await db('','DELETE');localStorage.removeItem(LAST);invitation='';stop();home();}catch(e){status(e.message);}},'tiny'));
 }
 async function signal(kind){if(!active||!online||room.flags?.paused)return;await write('signals/'+role,{kind,id:Date.now().toString(36),rev:room.control.rev});updateSession();}
 async function sharedAudio(){if(!host())return;await signal('audio');}
 async function pause(value){if(!host()||!online)return;if(stroke)return;if(Object.keys(pending).length){await flush();if(flushing||Object.keys(pending).length){status('انْتَظِرْ حَفْظَ الْكِتَابَةِ.');return;}}if(await write('flags/paused',value))sessionOverlay();}
 function sessionOverlay(){let mask=document.getElementById('session-mask');if(!active)return;if(!mask){mask=el('div',null,'session-mask');mask.id='session-mask';root.append(mask);}mask.replaceChildren();mask.hidden=!room.flags?.paused&&online;if(mask.hidden)return;stopSpeech();add(mask,el('div',room.flags?.paused?'☕':'📶','big'),el('h2',room.flags?.paused?'وَقْتُ اسْتِرَاحَةٍ قَصِيرَةٍ':'نَنْتَظِرُ عَوْدَةَ الِاتِّصَالِ'));if(host()&&online)mask.append(button('نُكْمِلُ مَعًا',()=>pause(false),'primary'));mask.append(button('مُغَادَرَةُ الْغُرْفَةِ',leave));}
 function updateSession(){if(!active)return;const other=role==='host'?'guest':'host',stamp=room.presence?.[other];const connected=typeof stamp==='number'&&Date.now()-stamp<30000;status(local?'جَلْسَةٌ مَحَلِّيَّةٌ':(connected?'🟢 '+names[other]+(other==='guest'?' مُتَّصِلَةٌ':' مُتَّصِلٌ'):'🟠 نَنْتَظِرُ اتِّصَالَ '+names[other]));
  const sig=room.signals?.host;if(sig&&sig.id!==lastSignal&&sig.rev===room.control.rev){lastSignal=sig.id;if(sig.kind==='audio'){const {l}=lesson();if(l&&room.control.phase==='learn')speak(lessonSpeech(l.cards[room.control.index]),l.cards[room.control.index].lang);else if(l&&room.control.phase==='quiz'){const t=task(),card=l.cards[t.card];speak(questionSpeech(card,DuoPlan.options(card,room.control.round)),card.lang);}else if(l&&room.control.phase==='write'){const card=l.cards[task().card];speak(card.word,card.lang);}}}
  const n=document.getElementById('session-note'),guest=room.signals?.guest;if(n)n.textContent=guest?.rev===room.control.rev?(guest.kind==='heart'?'💜 رُقَيَّة تُشَجِّعُ إِيسُو!':''):'';
  if(role==='guest'||local){for(const [key,value]of Object.entries(room.control.progress||{}))if(Number.isInteger(value)&&value>=1&&value<=3)state.best[key]=Math.max(state.best[key]||0,value);save();}sessionOverlay();
 }
 function schoolHome(){if(!active){lobby();return;}if(host()){if(['quiz','write'].includes(room.control.phase)&&!confirm('هَلْ نَعُودُ إِلَى الْمَوَادِّ؟ سَيَبْدَأُ النَّشَاطُ مِنْ جَدِيدٍ عِنْدَ فَتْحِهِ.'))return;control({phase:'pick'});}else status('إِيسُو يَخْتَارُ الْمَادَّةَ وَيُغَيِّرُ الدَّرْسَ لِلْجِهَازَيْنِ.');}
 function back(){if(!active){lobby();return true;}if(!host()){status('إِيسُو يَتَحَكَّمُ فِي التَّنَقُّلِ.');return true;}if(room.control.phase==='pick'||room.control.phase==='waiting')leave();else schoolHome();return true;}
 function subjects(){title('مَاذَا سَنَتَعَلَّمُ الْيَوْمَ؟',host()?'اِخْتَرْ مَادَّةً لِنَفْتَحَهَا مَعًا.':'إِيسُو يَخْتَارُ الْمَادَّةَ لَنَا.');const grid=el('div',null,'grid');SUBJECTS.forEach(s=>{const b=button('',()=>control({phase:'subject',subject:s.id}),'subject');b.disabled=!host();b.style.setProperty('--card',s.color);add(b,el('span',s.icon,'icon'),el('strong',s.name),el('small',s.desc));grid.append(b);});root.append(grid);}
 function sharedRewards(){title('⭐ إِنْجَازَاتُ رُقَيَّة','نَفْرَحُ مَعًا بِكُلِّ خُطْوَةٍ.');let sum=0;const panel=el('div',null,'panel');SUBJECTS.forEach(s=>s.lessons.forEach(l=>{const n=room.control.progress?.[l.id]||0;sum+=n;if(n)panel.append(el('p',l.title+' • '+'⭐'.repeat(n)));}));add(panel,el('h2','النُّجُومُ فِي غُرْفَتِنَا: '+sum));root.append(panel);if(host())root.append(button('نُكْمِلُ التَّعَلُّمَ',()=>control({phase:'pick'}),'primary'));}
 function render(){if(!active||!room?.control)return;const c=room.control,r=response(),stamp=c.rev+':'+!!r;if(stamp===view){if(drawRefresh)drawRefresh();updateSession();return;}view=stamp;if(c.phase!=='write'){pending={};pendingPath='';stroke=null;}shell();renderedPhase=c.phase;
  if(c.phase==='waiting'){title(host()?'غُرْفَتُنَا جَاهِزَةٌ 💌':'دَخَلْتِ مَعَ إِيسُو 💜',host()?'أَرْسِلِ الدَّعْوَةَ، ثُمَّ نَبْدَأُ بَعْدَ دُخُولِ رُقَيَّة.':'سَتَظْهَرُ الْمَوَادُّ بَعْدَ لَحَظَاتٍ.');if(host()){root.append(button('💌 أَرْسِلْ رَابِطَ الدَّعْوَةِ',shareInvite,'primary'));const badge=el('strong',null,'room-code');badge.textContent=id;add(root,el('p','رَمْزُ الْغُرْفَةِ لِلدُّخُولِ الْيَدَوِيِّ:'),badge);}updateSession();return;}
  if(c.phase==='pick'){subjects();updateSession();return;}
  if(c.phase==='rewards'){sharedRewards();updateSession();return;}
  if(c.phase==='subject'){const sub=SUBJECTS.find(x=>x.id===c.subject);if(!sub)return;title(sub.icon+' '+sub.name,host()?'اِخْتَرِ الدَّرْسَ لِنَتَعَلَّمَهُ مَعًا.':'إِيسُو يَخْتَارُ الدَّرْسَ لَنَا.');const list=el('div',null,'lesson-list');sub.lessons.forEach(l=>{const b=button(l.title,()=>control({subject:sub.id,lesson:l.id,phase:'learn',index:0,round:0,order:l.cards.map((_,i)=>i)}));b.disabled=!host();list.append(b);});root.append(list);updateSession();return;}
  const {s,l}=lesson();if(!l){title('تَحْتَاجُ الْجَلْسَةُ إِلَى نُسْخَةِ التَّطْبِيقِ نَفْسِهَا.');return;}current={subject:s,lesson:l};
  if(c.phase==='learn'){
   const card=l.cards[c.index];title(l.title,'الْبِطَاقَةُ '+(c.index+1)+' مِنْ '+l.cards.length);const p=el('section',null,'panel center');add(p,cardVisual(card),el('h2',card.word),el('p',card.detail,l.id==='add'?'equation':'muted'),button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 أَسْتَمِعُ مَرَّةً أُخْرَى',()=>host()?sharedAudio():speak(lessonSpeech(card),card.lang),'secondary'));root.append(p);
   if(role==='guest'||local){state.seen[l.id]=Math.max(state.seen[l.id]||0,c.index+1);save();}
   if(host()){const nav=el('div',null,'nav');if(c.index>0)nav.append(button('السَّابِقُ',()=>control({index:c.index-1})));if(c.index<l.cards.length-1)nav.append(button('التَّالِي',()=>control({index:c.index+1}),'primary'));else nav.append(button('🎯 نَبْدَأُ الْأَسْئِلَةَ',()=>start('quiz'),'primary'));add(root,nav,button('✏️ نَتَدَرَّبُ عَلَى الْكِتَابَةِ وَالرَّسْمِ',()=>start('write'),'secondary'));}else root.append(el('p','إِيسُو يُقَلِّبُ الْبِطَاقَاتِ.','center'));
  }else if(c.phase==='quiz')quiz();else if(c.phase==='write')board();else if(c.phase==='end')finishDuo();
  if(host()&&c.phase!=='end')root.append(button('اخْتِيَارُ دَرْسٍ آخَرَ',()=>{if(confirm('هَلْ نَتْرُكُ هَذَا النَّشَاطَ؟'))control({phase:'pick'});}));updateSession();
 }
 function start(phase){const {l}=lesson();control({phase,round:0,order:shuffle(l.cards.map((_,i)=>i)),guestCorrect:0,guestDone:0});}
 function headerTurn(t){const c=room.control,{l}=lesson();title('دَوْرُ '+names[t.role], 'الدَّوْرُ '+(c.round+1)+' مِنْ '+(l.cards.length*2));const p=el('p',mine(t.role)?(t.role==='guest'?'🌟 هَيَّا يَا رُقَيَّة، هَذَا دَوْرُكِ!':'🌟 هَيَّا يَا إِيسُو، هَذَا دَوْرُكَ!'):'👀 نُشَجِّعُ '+names[t.role]+' وَنَنْتَظِرُ دَوْرَنَا.','turn-banner');root.append(p);}
 function quiz(){const t=task(),{l}=lesson(),card=l.cards[t.card],opts=DuoPlan.options(card,room.control.round);headerTurn(t);const p=el('div',null,'panel center');p.append(el('h2',card.q,l.id==='add'?'equation':''));if(['compare','shapes','colors'].includes(l.id))p.append(cardVisual(card));if(l.id.startsWith('num'))p.append(el('div',card.detail,'count'));p.append(button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 السُّؤَالُ وَالْإِجَابَاتُ',()=>host()?sharedAudio():speak(questionSpeech(card,opts),card.lang),'secondary'));root.append(p);const choices=el('div',null,'choices');const r=response();opts.forEach((o,i)=>{const wrap=el('div',null,'answer-card');const b=button('',async()=>{if(busy||response()||!mine(t.role))return;busy=true;const ok=await write('responses/r'+room.control.rev,{role:t.role,value:o});busy=false;if(ok){view='';render();}},'choice');add(b,el('span',i+1,'answer-number'),el('span',optionPicture(o),'answer-picture'),el('span',o,'answer-label'));b.disabled=!mine(t.role)||!!r;if(r&&o===card.answer)b.classList.add('correct');if(r&&r.value===o&&o!==card.answer)b.classList.add('wrong');add(wrap,b,button('🔊 '+(i+1),()=>speak(optionSpeech(o,i,card.lang),card.lang),'listen-choice'));choices.append(wrap);});root.append(choices);if(r){root.append(el('p',r.value===card.answer?'إِجَابَةٌ صَحِيحَةٌ! أَحْسَنْتَ يَا إِيسُو، وَأَحْسَنْتِ يَا رُقَيَّة 🌟':'نَتَعَلَّمُ مَعًا. الْإِجَابَةُ الصَّحِيحَةُ: '+card.answer,'feedback'));if(host())root.append(button('التَّالِي',next,'primary'));else root.append(el('p','نَنْتَظِرُ إِيسُو لِنُكْمِلَ.'));}}
 async function next(){const c=room.control,t=task(),{l}=lesson(),r=response();if(!r)return;const right=c.phase==='quiz'&&r.value===l.cards[t.card].answer;const done=(c.guestDone||0)+(t.role==='guest'?1:0),correct=(c.guestCorrect||0)+(t.role==='guest'&&right?1:0);const progress={...(c.progress||{})};if(c.phase==='quiz'&&c.round+1===l.cards.length*2&&done===l.cards.length){const stars=correct===l.cards.length?3:correct>=Math.ceil(l.cards.length/2)?2:1;progress[l.id]=Math.max(progress[l.id]||0,stars);}await control({progress,round:c.round+1,guestDone:done,guestCorrect:correct,phase:c.round+1===l.cards.length*2?'end':c.phase,finished:c.phase});}
 function finishDuo(){const {l}=lesson(),c=room.control;title('أَحْسَنْتُمَا! 🎉','تَدَرَّبَ كُلٌّ مِنْكُمَا عَلَى جَمِيعِ الْبِطَاقَاتِ.');if(c.finished==='quiz'&&c.guestDone===l.cards.length){const stars=c.guestCorrect===l.cards.length?3:c.guestCorrect>=Math.ceil(l.cards.length/2)?2:1;if(local||role==='guest'){state.best[l.id]=Math.max(state.best[l.id]||0,stars);save();}add(root,el('p','نُجُومُ رُقَيَّة: '+'⭐'.repeat(stars),'stars'),el('p','الْإِجَابَاتُ الصَّحِيحَةُ لِرُقَيَّة: '+c.guestCorrect+' مِنْ '+l.cards.length));}else root.append(el('p','رَاجِعَا الْكِتَابَةَ مَعًا؛ لَا يُقَيِّمُ التَّطْبِيقُ خَطَّ الْيَدِ تِلْقَائِيًّا.'));if(host())add(root,button('✏️ نَكْتُبُ مَعًا',()=>start('write'),'primary'),button('🎯 نُجِيبُ عَنِ الْأَسْئِلَةِ',()=>start('quiz'),'secondary'),button('دَرْسٌ آخَرُ',()=>control({phase:'pick'})));}
 function board(){const t=task(),{s,l}=lesson(),card=l.cards[t.card],c=room.control;headerTurn(t);const target=DuoPlan.target(s,card);add(root,el('p',['arabic','english','math'].includes(s.id)?'نَكْتُبُ النَّمُوذَجَ عَلَى السَّطْرِ.':'نَرْسُمُ مَا يُعَبِّرُ عَنِ الْبِطَاقَةِ، وَنَتَحَدَّثُ عَنْهَا.','center'),el('h2',target,'writing-target'),button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 أَسْتَمِعُ',()=>host()?sharedAudio():speak(card.word,card.lang),'secondary'));const canvas=el('canvas',null,'trace shared-board');canvas.width=900;canvas.height=560;canvas.setAttribute('aria-label','سبورة مشتركة للكتابة');root.append(canvas);const ctx=canvas.getContext('2d'),path='boards/r'+c.rev;pendingPath=path;pending={};canvasStrokes=mine(t.role)?{...(room.boards?.['r'+c.rev]||{})}:{};stroke=null;
  function redraw(){ctx.clearRect(0,0,900,560);ctx.fillStyle='#fffdf9';ctx.fillRect(0,0,900,560);const ys=s.id==='english'?[160,260,360,440]:[230,410];ys.forEach((y,i)=>{ctx.strokeStyle=i===2?'#9d83cb':'#d5cbdf';ctx.lineWidth=2;ctx.setLineDash(s.id==='english'&&i===1?[12,9]:[]);ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(870,y);ctx.stroke();});ctx.setLineDash([]);const strokes={...(room.boards?.['r'+c.rev]||{}),...canvasStrokes,...pending};Object.values(strokes).forEach(st=>{if(!st||!Array.isArray(st.points)||!/^#[a-f0-9]{6}$/i.test(st.color))return;ctx.strokeStyle=st.color;ctx.fillStyle=st.color;ctx.lineWidth=7;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();st.points.forEach((p,i)=>{if(i===0)ctx.moveTo(p[0]*900,p[1]*560);else ctx.lineTo(p[0]*900,p[1]*560);});ctx.stroke();if(st.points.length===1){ctx.beginPath();ctx.arc(st.points[0][0]*900,st.points[0][1]*560,3.5,0,Math.PI*2);ctx.fill();}});}
  drawRefresh=redraw;
  const pos=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
  canvas.onpointerdown=e=>{if(!mine(t.role)||response()||(!local&&!online)||Object.keys(canvasStrokes).length>=150)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);stroke='s'+Object.keys(canvasStrokes).length;canvasStrokes[stroke]={role:t.role,color:ink,points:[pos(e)]};pending[stroke]=canvasStrokes[stroke];redraw();setTimeout(flush,150);};
  canvas.onpointermove=e=>{if(!stroke||room.flags?.paused||!online)return;e.preventDefault();const st=canvasStrokes[stroke];if(st.points.length>=300)return;st.points.push(pos(e));pending[stroke]=st;redraw();setTimeout(flush,150);};canvas.onpointerup=canvas.onpointercancel=()=>{stroke=null;flush();};
  const palette=el('div',null,'palette');['#7753c7','#277fc5','#369a78','#eb6487','#30384d'].forEach(color=>{const b=button('',()=>ink=color,'swatch');b.style.background=color;b.setAttribute('aria-label',color);palette.append(b);});root.append(palette);if(mine(t.role)&&!response()){add(root,button('تَرَاجُعٌ عَنْ آخِرِ خَطٍّ',async()=>{if(flushing||stroke||Object.keys(pending).length)return;const keys=Object.keys(canvasStrokes);if(!keys.length)return;const last=keys.at(-1);if(await write(path+'/'+last,null)){delete canvasStrokes[last];redraw();}},'secondary'),button('انْتَهَيْتُ ✅',async()=>{if(busy)return;busy=true;await flush();if(flushing||Object.keys(pending).length){status('انْتَظِرْ حَفْظَ الْكِتَابَةِ، ثُمَّ اضْغَطْ مَرَّةً أُخْرَى.');busy=false;return;}if(await write('responses/r'+c.rev,{role:t.role,value:'done'})){view='';render();}busy=false;},'primary'));}if(response()){root.append(el('p','نُرَاجِعُ الْكِتَابَةَ مَعًا 💜'));if(host())root.append(button('الدَّوْرُ التَّالِي',next,'primary'));}redraw();
 }
 async function flush(){if(flushing||!Object.keys(pending).length||!active)return;flushing=true;const batch=JSON.parse(JSON.stringify(pending)),path=pendingPath,e=epoch;pending={};try{if(local){Object.entries(batch).forEach(([k,v])=>putLocal(path+'/'+k,v));}else{await db(path,'PATCH',batch);if(e!==epoch)return;Object.entries(batch).forEach(([k,v])=>putLocal(path+'/'+k,v));} }catch(e){if(active&&e===epoch&&path===pendingPath)pending={...batch,...pending};status('لَمْ تُحْفَظْ بَعْضُ الْخُطُوطِ. اِنْتَظِرْ عَوْدَةَ الِاتِّصَالِ.');}finally{flushing=false;if(active&&e===epoch&&Object.keys(pending).length)setTimeout(flush,1000);}}
 return {lobby,leave,home:schoolHome,back,acceptInvite,extractInvite,isActive:()=>active,configValid};
})();
home=()=>Duo.home();
document.getElementById('home').onclick=home;
window.appBack=()=>Duo.back();
window.schoolInvite=code=>Duo.acceptInvite(code);
const invite=window.location?Duo.extractInvite(window.location.href):'';
if(invite)Duo.acceptInvite(invite);else Duo.lobby();
if(window.Android?.getInvite){const incoming=Android.getInvite();if(incoming)Duo.acceptInvite(incoming);}
window.addEventListener?.('hashchange',()=>Duo.acceptInvite(window.location.href));
