'use strict';
/* Each player completes every card; role queues are offset and interleaved. */
const DuoPlan={
 quiz(cards,order){const offset=order.length>2?2:1;return order.flatMap((card,i)=>[{card,role:'host'},{card:order[(i+offset)%order.length],role:'guest'}]);},
 examples(subject,card){return card.writing!==undefined?card.writing:[subject.id==='math'?card.front:card.word];},
 tasks(cards,order,subject){const pairs=this.quiz(cards,order),queue=role=>pairs.filter(t=>t.role===role).flatMap(t=>{const c=cards[t.card],writing=this.examples(subject,c);return [...(['draw','dictation'].includes(c.practice)?[]:[{...t,kind:c.practice==='build'?'build':'choice'}]),...(c.practice==='oral'?[{...t,kind:'oral'}]:[]),...writing.map((target,position)=>({...t,kind:'write',target,position}))];});const a=queue('host'),b=queue('guest');return a.flatMap((t,i)=>[t,b[i]]);},
 options(card,task){const a=[...card.options];const n=task%a.length;return a.slice(n).concat(a.slice(0,n));},
 target(subject,card){return subject.id==='math'?card.front:card.word;}
};
const Duo=(()=>{
 const CFG='roqaya_firebase_v2', AUTH='roqaya_auth_v2', LAST='roqaya_room_v3';
 let cfg=null,auth=null,room=null,id='',role='host',local=false,timer=null,active=false,epoch=0,view='',busy=false,online=true,drawRefresh=null,flushing=false;
 let pending={},pendingPath='',canvasStrokes={},stroke=null,ink='#7753c7',renderedPhase='',boardStream=null,streamRev=-1,flushTimer=null,lastFeedbackRev=-1;
 let readGeneration=0,lastWake=0,flushJob=null;const readRequests=new Set();
 const names={host:'إِيسُو',guest:'رُقَيَّة'};
 try{cfg=JSON.parse(localStorage.getItem(CFG));auth=JSON.parse(localStorage.getItem(AUTH));}catch(e){}
 if(!configValid(cfg))cfg=window.SCHOOL_CONFIG||null;
 let invitation='',lastSignal='',lastHeartbeat=0,finishedRev=0;
 const webBase=()=>{try{const u=new URL(cfg?.webURL||window.location.href);return u.protocol==='https:'&&u.hostname!=='roqaya.local'&&!u.username&&!u.password?u.origin+u.pathname:'';}catch(e){return '';}};
 function configValid(c){try{const u=new URL(c.databaseURL);return /^[A-Za-z0-9_-]{20,}$/.test(c.apiKey)&&u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&/^\/[\/]?$/.test(u.pathname)&&/^[a-z0-9-]+\.(firebaseio\.com|[a-z0-9-]+\.firebasedatabase\.app)$/.test(u.hostname);}catch(e){return false;}}
 function readInput(label,type='text'){const wrap=el('label',label,'field'),input=el('input');input.type=type;input.autocomplete='off';input.spellcheck=false;input.dir='ltr';wrap.append(input);return [wrap,input];}
 function status(text){const e=document.getElementById('duo-status');if(e)e.textContent=text;}
 async function jsonFetch(url,options={}){const controller=new AbortController();const reading=!options.method||options.method==='GET';if(reading)readRequests.add(controller);const timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{...options,...(reading?{cache:'no-store'}:{}),signal:controller.signal});if(!r.ok)throw Error(r.status===401||r.status===403?'تَعَذَّرَ الدُّخُولُ. رَاجِعْ إِعْدَادَاتِ الْخِدْمَةِ وَصَلَاحِيَّةَ الْجَلْسَةِ.':'تَعَذَّرَ الِاتِّصَالُ. حَاوِلْ مَرَّةً أُخْرَى.');return await r.json();}finally{clearTimeout(timeout);readRequests.delete(controller);}}
 async function token(){
  if(auth&&auth.project===cfg.apiKey&&auth.expiry>Date.now()+60000)return auth.token;
  if(auth&&auth.project===cfg.apiKey&&auth.refresh){const d=await jsonFetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(cfg.apiKey),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=refresh_token&refresh_token='+encodeURIComponent(auth.refresh)});auth={project:cfg.apiKey,uid:d.user_id,token:d.id_token,refresh:d.refresh_token,expiry:Date.now()+Number(d.expires_in)*1000};}
  else{const d=await jsonFetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(cfg.apiKey),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});auth={project:cfg.apiKey,uid:d.localId,token:d.idToken,refresh:d.refreshToken,expiry:Date.now()+Number(d.expiresIn)*1000};}
  localStorage.setItem(AUTH,JSON.stringify(auth));return auth.token;
 }
 async function db(path,method='GET',data){const t=await token();return jsonFetch(cfg.databaseURL.replace(/\/$/,'')+'/studyRoomsV3/'+id+(path?'/'+path:'')+'.json?auth='+encodeURIComponent(t),{method,headers:{'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});}
 function stop(){active=false;epoch++;cancelReads();if(boardStream)boardStream.close();boardStream=null;streamRev=-1;clearTimeout(flushTimer);flushTimer=null;clearTimeout(timer);timer=null;drawRefresh=null;view='';pending={};stroke=null;}
 function leave(){if(active&&!confirm('هَلْ تُرِيدُ مُغَادَرَةَ الْجَلْسَةِ؟'))return;invitation='';stop();home();}
 function lobby(){stop();reset('duo');title('مَدْرَسَةُ رُقَيَّة 💜','إِيسُو وَرُقَيَّة • نَتَعَلَّمُ مَعًا مِنَ الْبِدَايَةِ إِلَى النِّهَايَةِ.');
  const hero=el('div',null,'hero center');add(hero,el('div','👨‍👧','big'),el('h2',invitation?'إِيسُو يَنْتَظِرُكِ!':'مَوْعِدُنَا لِنَتَعَلَّمَ مَعًا'),el('p','غُرْفَةٌ وَاحِدَةٌ، وَالدَّرْسُ نَفْسُهُ عَلَى الْجِهَازَيْنِ.'));root.append(hero);
  const panel=el('section',null,'panel');
  if(configValid(cfg)){
   if(!invitation)panel.append(button('👨 إِيسُو: أَنْشِئْ غُرْفَةَ الْمُذَاكَرَةِ',createRoom,'primary room-create'));
   const [w,input]=readInput('رَابِطُ الدَّعْوَةِ أَوْ رَمْزُ الْغُرْفَةِ');input.value=invitation;input.placeholder='الصقي دعوة إيسو هنا';add(panel,w,button('👧 رُقَيَّة: ادْخُلِي مَعَ إِيسُو',()=>joinRoom(extractInvite(input.value)),'primary room-join'));
   if(invitation&&!window.Android){const link=el('a','فَتْحُ الدَّعْوَةِ فِي تَطْبِيقِ أَنْدْرُويد','app-open');link.href='roqayaschool://join?room='+invitation;panel.append(link);}
   const last=localStorage.getItem(LAST);if(last)panel.append(button('الْعَوْدَةُ إِلَى غُرْفَتِنَا',()=>resume(last),'secondary'));
  }else panel.append(el('p','يُكْمِلُ إِيسُو إِعْدَادَ التَّطْبِيقِ أَوَّلًا.'));
  const msg=el('p','','muted');msg.id='duo-status';add(root,panel,msg,button('⚙️ إِعْدَادَاتُ وَلِيِّ الْأَمْرِ',settings,'tiny'));
 }
 function validRoomCode(code){return /^([0-9]{6}|[a-f0-9]{32})$/i.test(code||'');}
 function normalizeRoomCode(value){return String(value||'').replace(/[٠-٩]/g,n=>String(n.charCodeAt(0)-1632)).replace(/[۰-۹]/g,n=>String(n.charCodeAt(0)-1776)).replace(/\s/g,'').toLowerCase();}
 function extractInvite(value){const text=String(value).trim(),code=normalizeRoomCode(text);if(validRoomCode(code))return code;try{const u=new URL(text),room=normalizeRoomCode(new URLSearchParams(u.hash.slice(1)).get('room')||u.searchParams.get('room'));return validRoomCode(room)?room:'';}catch(e){return '';}}
 function acceptInvite(value){const code=extractInvite(value);if(!code)return;if(active&&id===code)return;if(active&&!confirm('هَلْ نَفْتَحُ الدَّعْوَةَ الْجَدِيدَةَ؟'))return;invitation=code;lobby();}
 async function shareInvite(){const base=webBase();if(!base){status('يَلْزَمُ إِضَافَةُ رَابِطِ نُسْخَةِ الْوِيبِ مَرَّةً وَاحِدَةً مِنْ إِعْدَادَاتِ وَلِيِّ الْأَمْرِ.');return;}const link=base+'#room='+id;const text='يَا رُقَيَّة، تَعَالَيْ نَتَعَلَّمْ مَعًا 💜\n'+link;
  if(window.Android?.share){Android.share(text);return;}
  if(navigator.share){try{await navigator.share({title:'دعوة إيسو للمذاكرة',text:'يَا رُقَيَّة، تَعَالَيْ نَتَعَلَّمْ مَعًا 💜',url:link});return;}catch(e){if(e.name==='AbortError')return;}}
  try{await navigator.clipboard.writeText(link);status('نُسِخَ رَابِطُ الدَّعْوَةِ. أَرْسِلْهُ لِرُقَيَّة.');}catch(e){const box=el('textarea');box.value=link;box.readOnly=true;root.append(box);box.focus();box.select();status('حَدِّدِ الرَّابِطَ وَانْسَخْهُ.');}
 }
 function settings(){reset('duo');title('إِعْدَادَاتُ وَلِيِّ الْأَمْرِ','تُضْبَطُ مَرَّةً وَاحِدَةً قَبْلَ أَوَّلِ جَلْسَةٍ.');const [w1,k]=readInput('Web API Key'),[w2,u]=readInput('Realtime Database URL'),[w3,web]=readInput('رابط نسخة التطبيق على الويب — لدعوة رقية');k.value=cfg?.apiKey||'';u.value=cfg?.databaseURL||'';web.value=cfg?.webURL||webBase();add(root,w3,el('p','اِنْشُرْ مِلَفَّاتِ web وَأَضِفْ قَوَاعِدَ studyRoomsV3 مَرَّةً وَاحِدَةً. إِعْدَادَاتُ الْمَشْرُوعِ الْعَامَّةُ مَوْجُودَةٌ بِالْفِعْلِ.','muted'),w1,w2,button('حِفْظٌ',()=>{const c={apiKey:k.value.trim(),databaseURL:u.value.trim().replace(/\/$/,''),webURL:web.value.trim()};if(!configValid(c)){alert('تَأَكَّدْ مِنْ بَيَانَاتِ الْخِدْمَةِ.');return;}if(c.webURL){try{const x=new URL(c.webURL);if(x.protocol!=='https:'||x.hostname==='roqaya.local'||x.username||x.password||x.hash||x.search)throw Error();}catch(e){alert('أَدْخِلْ رَابِطَ HTTPS لِنُسْخَةِ التَّطْبِيقِ، دُونَ رَمْزِ غُرْفَةٍ.');return;}}if(cfg?.apiKey!==c.apiKey||cfg?.databaseURL!==c.databaseURL){auth=null;localStorage.removeItem(AUTH);localStorage.removeItem(LAST);}cfg=c;localStorage.setItem(CFG,JSON.stringify(c));lobby();},'primary'),button('رُجُوعٌ',lobby));backupPanel();}
 function backupPanel(){const box=el('textarea');box.value=JSON.stringify(state);box.setAttribute('aria-label','نسخة التقدم');add(root,el('h3','نُسْخَةُ التَّقَدُّمِ الْمَحْفُوظَةِ'),box,button('تَحْدِيدٌ لِلنَّسْخِ',()=>{box.focus();box.select();}),button('اِسْتِعَادَةٌ',()=>{try{const x=JSON.parse(box.value),ids=ALL_SUBJECTS.flatMap(s=>s.lessons.map(l=>l.id));if(!valid(x)||Object.keys(x.best).some(k=>!ids.includes(k)||x.best[k]>3)||Object.keys(x.seen).some(k=>!ids.includes(k)))throw Error();if(confirm('هَلْ نَسْتَعِيدُ هَذِهِ النَّتَائِجَ؟')){state=x;save();settings();}}catch(e){alert('نُسْخَةٌ غَيْرُ صَالِحَةٍ.');}}));}
 function initial(){return {phase:'waiting',rev:1,round:0,activeRole:'host',progress:{},course:state.course||Curriculum.defaults()};}
 function sixDigits(){const b=new Uint32Array(1),limit=0x100000000-(0x100000000%900000);do{crypto.getRandomValues(b);}while(b[0]>=limit);return String(100000+(b[0]%900000));}
 async function reserveRoom(){const t=await token(),url=cfg.databaseURL.replace(/\/$/,'')+'/studyRoomsV3/'+id+'.json?auth='+encodeURIComponent(t),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{method:'PUT',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify(room)});if(r.status===403)return false;if(!r.ok)throw Error('تَعَذَّرَ إِنْشَاءُ الْغُرْفَةِ (رمز '+r.status+').');return true;}finally{clearTimeout(timeout);}}
 async function createRoom(){if(busy)return;busy=true;status('جَارٍ إِنْشَاءُ الْجَلْسَةِ…');try{local=false;await token();role='host';room={hostUid:auth.uid,createdAt:{'.sv':'timestamp'},expiresAt:Date.now()+2*60*60*1000,control:initial(),presence:{host:{'.sv':'timestamp'}}};let created=false;for(let attempt=0;attempt<8&&!created;attempt++){id=sixDigits();created=await reserveRoom();}if(!created)throw Error('رَفَضَتْ Firebase إِنْشَاءَ الْغُرْفَةِ. تَأَكَّدْ أَنَّ قَوَاعِدَ الْأَرْقَامِ السِّتَّةِ مَنْشُورَةٌ.');localStorage.setItem(LAST,id);activate();}catch(e){status(e.message||'تَعَذَّرَ إِنْشَاءُ الْغُرْفَةِ.');}finally{busy=false;}}
 async function joinRoom(code){if(busy)return;id=normalizeRoomCode(code);if(!validRoomCode(id)){status('الرَّمْزُ غَيْرُ صَحِيحٍ. أَدْخِلْ سِتَّةَ أَرْقَامٍ أَوِ اسْتَخْدِمْ رَابِطَ الدَّعْوَةِ.');return;}busy=true;status('جَارٍ الِانْضِمَامُ…');try{local=false;await token();await db('guestUid','PUT',auth.uid);role='guest';room=await db('');if(room.hostUid===auth.uid)role='host';localStorage.setItem(LAST,id);activate();}catch(e){status(e.message);}finally{busy=false;}}
 async function resume(code){if(busy)return;busy=true;try{local=false;id=code;await token();room=await db('');if(!room)throw Error('انْتَهَتِ الْجَلْسَةُ. أَنْشِئْ جَلْسَةً جَدِيدَةً.');role=room.hostUid===auth.uid?'host':'guest';activate();}catch(e){status(e.message);}finally{busy=false;}}
 function activate(){invitation='';lastSignal='';lastHeartbeat=0;finishedRev=0;active=true;online=true;view='';epoch++;render();poll(epoch);}

 function cancelReads(){readGeneration++;clearTimeout(timer);timer=null;for(const request of readRequests)request.abort();readRequests.clear();}
 function closeBoard(){if(boardStream)boardStream.close();boardStream=null;streamRev=-1;}
 function suspend(){if(!active||local)return;lastWake=0;cancelReads();closeBoard();stroke=null;stopSpeech();flush();}
 function reconnect(force=false){if(!active||local||document.visibilityState==='hidden')return;const now=Date.now();if(!force&&now-lastWake<500)return;lastWake=now;cancelReads();closeBoard();lastHeartbeat=0;online=false;sessionOverlay();poll(epoch,readGeneration);}
 async function poll(e,g=readGeneration){if(!active||local||(e!==epoch||g!==readGeneration))return;try{const [ctl,guest,flags,signals,presence]=await Promise.all([db('control'),db('guestUid'),db('flags'),db('signals'),db('presence')]);if((e!==epoch||g!==readGeneration)||!active)return;let r=ctl?{...room,control:ctl,guestUid:guest,flags,signals,presence}:null;if(ctl&&['quiz','write'].includes(ctl.phase)&&!BOOK.lessons.some(l=>l.id===ctl.lesson)){const response=await db('responses/r'+ctl.rev);r.responses={['r'+ctl.rev]:response||(ctl.rev===room.control.rev?room.responses?.['r'+ctl.rev]:null)};const sub=SUBJECTS.find(x=>x.id===ctl.subject),lessonCard=sub?.lessons.find(x=>x.id===ctl.lesson),plan=lessonCard?DuoPlan.tasks(lessonCard.cards,ctl.order,sub):[];if(ctl.phase==='quiz'&&plan[ctl.round]?.kind==='build')r.arrangements={['r'+ctl.rev]:await db('arrangements/r'+ctl.rev)};if(ctl.phase==='write'||(ctl.phase==='quiz'&&plan[ctl.round]?.kind==='write'))r.boards=boardStream&&streamRev===ctl.rev?room.boards:{['r'+ctl.rev]:await db('boards/r'+ctl.rev)};}if((e!==epoch||g!==readGeneration)||!active)return;if(!r){stop();lobby();status('انْتَهَتِ الْجَلْسَةُ.');return;}if(!room||r.control.rev>=room.control.rev)room=r;online=true;if(Date.now()-lastHeartbeat>10000){try{await db('presence/'+role,'PUT',{'.sv':'timestamp'});lastHeartbeat=Date.now();}catch(ignore){/* Presence is advisory; readable room state still means connected. */}}if(e!==epoch||g!==readGeneration)return;render();updateSession();if(lesson().l&&!lesson().l.bookExact&&['quiz','write'].includes(room.control.phase)&&(room.control.phase==='write'||task()?.kind==='write'))listenBoard(room.control.rev);if(Object.keys(pending).length)scheduleFlush();if(host()&&room.guestUid&&room.control.phase==='waiting')await control({phase:'pick'});}catch(err){if((e!==epoch||g!==readGeneration))return;online=false;status('🟠 انْقَطَعَ الِاتِّصَالُ. نُعِيدُ الْمُحَاوَلَةَ…');sessionOverlay();}if(active&&e===epoch&&g===readGeneration)timer=setTimeout(()=>poll(e,g),1000);}
 function host(){return local||role==='host';}
 function mine(r){return !room?.flags?.paused&&(local||r===role);}
 function lesson(){const c=room.control,s=SUBJECTS.find(x=>x.id===c.subject);return {s,l:s?.lessons.find(x=>x.id===c.lesson)};}
 function tasks(){const {s,l}=lesson();if(!l||l.bookExact)return [];return room.control.phase==='write'?DuoPlan.quiz(l.cards,room.control.order).map(t=>({...t,kind:'write'})):DuoPlan.tasks(l.cards,room.control.order,s);}
 function task(){return tasks()[room.control.round];}
 function response(){return room.responses?.['r'+room.control.rev]||null;}
 function putLocal(path,value){const a=path.split('/');let o=room;for(let i=0;i<a.length-1;i++)o=o[a[i]]||(o[a[i]]={});o[a.at(-1)]=value;}
 async function write(path,value){if(!active)return false;if(!local&&!online){status('انْتَظِرْ عَوْدَةَ الِاتِّصَالِ.');return false;}const e=epoch;try{if(!local)await db(path,'PUT',value);if(e!==epoch||!active)return false;putLocal(path,value);return true;}catch(e){online=false;status('لَمْ يُحْفَظِ التَّغْيِيرُ. حَاوِلْ بَعْدَ عَوْدَةِ الِاتِّصَالِ.');return false;}}
 async function control(patch){if(!host()||busy||room.flags?.paused||(!local&&!room.guestUid&&patch.phase!=='waiting'))return;if(room.control.phase==='write'||(room.control.phase==='quiz'&&task()?.kind==='write')){stroke=null;await flush();if(Object.keys(pending).length)await flush();if(flushing||Object.keys(pending).length){const exiting=patch.phase&&!['quiz','write','end'].includes(patch.phase);if(!exiting||!confirm('تَعَذَّرَ حِفْظُ بَعْضِ الْخُطُوطِ. هَلْ نَتْرُكُهَا وَنَرْجِعُ لِلدُّرُوسِ؟')){status('تَعَذَّرَ حِفْظُ الْخُطُوطِ. أَعِدِ الْمُحَاوَلَةَ أَوِ اخْتَرِ الرُّجُوعَ لِلدُّرُوسِ.');return;}pending={};clearTimeout(flushTimer);flushTimer=null;}}busy=true;const c={...room.control,...patch,rev:room.control.rev+1};if(patch.readingStep===undefined&&(patch.phase!==undefined||patch.index!==undefined||patch.lesson!==undefined))c.readingStep=0;if(['quiz','write'].includes(c.phase)&&!lesson().l?.bookExact){const {s,l}=lesson();c.activeRole=(c.phase==='write'?DuoPlan.quiz(l.cards,c.order):DuoPlan.tasks(l.cards,c.order,s))[c.round]?.role||'host';}else c.activeRole='host';if(await write('control',c)){view='';render();}busy=false;}
 function shell(){reset('duo');drawRefresh=null;const top=el('div',null,'duo-top');add(top,el('strong','مَدْرَسَةُ رُقَيَّة 💜'),button('مُغَادَرَةٌ',leave));root.append(top);const msg=el('p','','muted');msg.id='duo-status';root.append(msg);
  const row=el('div',null,'session-tools');if(host()){
   if(!local)row.append(button('💌 دَعْوَةُ رُقَيَّة',shareInvite));
   if(room.guestUid||local)add(row,button('🏡 الرَّئِيسِيَّةُ',schoolHome),button('☕ اِسْتِرَاحَةٌ',()=>pause(true)));
  }else add(row,button('💜 أَحْسَنْتَ يَا إِيسُو',()=>signal('heart')));
  root.append(row);const note=el('p','','session-note');note.id='session-note';note.setAttribute('aria-live','polite');root.append(note);
  if(host()&&!local)root.append(button('إِنْهَاءُ الْجَلْسَةِ وَحَذْفُهَا',async()=>{if(!confirm('هَلْ نُنْهِي الْجَلْسَةَ وَنَحْذِفُ بَيَانَاتِهَا؟'))return;try{await db('','DELETE');localStorage.removeItem(LAST);invitation='';stop();home();}catch(e){status(e.message);}},'tiny'));
 }
 async function signal(kind){if(!active||!online||room.flags?.paused)return;await write('signals/'+role,{kind,id:Date.now().toString(36),rev:room.control.rev});updateSession();}
 async function sharedAudio(){if(!host())return;await signal('audio');}
 async function pause(value){if(!host()||!online)return;if(stroke)return;if(Object.keys(pending).length){await flush();if(flushing||Object.keys(pending).length){status('انْتَظِرْ حَفْظَ الْكِتَابَةِ.');return;}}if(await write('flags/paused',value))sessionOverlay();}
 function sessionOverlay(){let mask=document.getElementById('session-mask');if(!active)return;if(!mask){mask=el('div',null,'session-mask');mask.id='session-mask';root.append(mask);}mask.replaceChildren();mask.hidden=!room.flags?.paused&&online;if(mask.hidden)return;stopSpeech();add(mask,el('div',room.flags?.paused?'☕':'📶','big'),el('h2',room.flags?.paused?'وَقْتُ اسْتِرَاحَةٍ قَصِيرَةٍ':'نَنْتَظِرُ عَوْدَةَ الِاتِّصَالِ'));if(host()&&online)mask.append(button('نُكْمِلُ مَعًا',()=>pause(false),'primary'));if(!online)mask.append(button('إِعَادَةُ الِاتِّصَالِ',()=>reconnect(true),'primary'));mask.append(button('مُغَادَرَةُ الْغُرْفَةِ',leave));}
 function updateSession(){if(!active)return;const other=role==='host'?'guest':'host',stamp=room.presence?.[other];const connected=typeof stamp==='number'&&Date.now()-stamp<30000;status(local?'جَلْسَةٌ مَحَلِّيَّةٌ':(connected?'🟢 '+names[other]+(other==='guest'?' مُتَّصِلَةٌ':' مُتَّصِلٌ'):'🟠 نَنْتَظِرُ اتِّصَالَ '+names[other]));
  const sig=room.signals?.host;if(sig&&sig.id!==lastSignal&&sig.rev===room.control.rev){lastSignal=sig.id;if(sig.kind==='audio'&&!lesson().l?.bookExact){const {l}=lesson(),c=room.control;if(l&&c.phase==='learn')speak(lessonSpeech(l.cards[c.index]),l.cards[c.index].lang);else if(l&&['quiz','write'].includes(c.phase)){const t=task(),card=l.cards[t.card];if(c.phase==='write'||t.kind==='write')speak(t.target||card.word,card.lang);else if(t.kind==='build')speak(card.word+'. '+card.q,card.lang);else if(t.kind==='oral')speak(card.word,card.lang);else speak(questionSpeech(card,DuoPlan.options(card,c.round)),card.lang);}}}
  if(Curriculum.valid(room.control.course)){state.course={...room.control.course,ratings:room.control.course.ratings||{}};save();}
  const n=document.getElementById('session-note'),guest=room.signals?.guest;if(n)n.textContent=guest?.rev===room.control.rev?(guest.kind==='heart'?'💜 رُقَيَّة تُشَجِّعُ إِيسُو!':''):'';
  if(role==='guest'||local){for(const [key,value]of Object.entries(room.control.progress||{}))if(Number.isInteger(value)&&value>=1&&value<=3)state.best[key]=Math.max(state.best[key]||0,value);save();}sessionOverlay();
 }
 function schoolHome(){if(!active){lobby();return;}if(host()){control({phase:'pick'});}else status('إِيسُو يَخْتَارُ الْمَادَّةَ وَيُغَيِّرُ الدَّرْسَ لِلْجِهَازَيْنِ.');}
 function back(){if(!active){lobby();return true;}if(!host()){status('إِيسُو يَتَحَكَّمُ فِي التَّنَقُّلِ.');return true;}if(room.control.phase==='pick'||room.control.phase==='waiting')leave();else if(room.control.phase==='write'||(room.control.phase==='quiz'&&task()?.kind==='write'))control({phase:'subject',subject:room.control.subject});else schoolHome();return true;}
 function course(){return Curriculum.valid(room.control.course)?{...room.control.course,ratings:room.control.course.ratings||{}}:Curriculum.defaults();}
 async function setCourse(patch,nav={}){await control({...nav,course:{...course(),...patch}});}
 function courseButton(label,fn,cls='secondary'){const b=button(label,fn,cls);b.disabled=!host();return b;}
 function openCourseLesson(id){const item=Curriculum.lesson(id);if(!item||item.subject.id!=='arabic')return;if(item.lesson.optional&&Curriculum.missing(course(),id).length){status('نُتْقِنُ الدُّرُوسَ السَّابِقَةَ أَوَّلًا، ثُمَّ نَفْتَحُ هَذَا النَّشَاطَ الِاخْتِيَارِيَّ.');return;}control({phase:'learn',subject:item.subject.id,lesson:id,index:0,round:0,order:item.lesson.cards.map((_,i)=>i)});}
 function ratingPanel(id){const panel=el('section',null,'rating-panel');const saved=course().ratings[id];add(panel,el('h3','مُلَاحَظَةُ إِيسُو'),el('p',Curriculum.label(saved?.level)+(saved?.level===3?' • أَيَّامُ الْأَدَاءِ الْمُسْتَقِلِّ: '+saved.days+' / ٢':''),'muted'));const row=el('div',null,'rating-actions');[1,2,3].forEach(level=>row.append(courseButton(Curriculum.label(level),()=>control({course:Curriculum.rate(course(),id,level)}),saved?.level===level?'primary':'secondary')));panel.append(row);return panel;}
 function subjects(){title('بِدَايَةٌ جَدِيدَةٌ','لَا تُوجَدُ مَوَادُّ أَوْ دُرُوسٌ حَالِيًّا.');}
 function sharedRewards(){title('⭐ إِنْجَازَاتُ رُقَيَّة','نَفْرَحُ مَعًا بِكُلِّ خُطْوَةٍ.');let sum=0;const panel=el('div',null,'panel');SUBJECTS.forEach(s=>s.lessons.forEach(l=>{const n=room.control.progress?.[l.id]||0;sum+=n;if(n)panel.append(el('p',l.title+' • '+'⭐'.repeat(n)));}));add(panel,el('h2','النُّجُومُ فِي غُرْفَتِنَا: '+sum));root.append(panel);if(host())root.append(button('نُكْمِلُ التَّعَلُّمَ',()=>control({phase:'pick'}),'primary'));}
 let bookFeedbackRev=-1;
 function bookControl(patch){if(!host()||!online||room.flags?.paused)return;return control(patch);}
 function bookOpen(l){return bookControl({phase:'learn',subject:'arabic',lesson:l.id,index:0,round:0,order:[0],readingStep:0,guestCorrect:0,guestDone:0});}
 function bookPicture(page,rect=null){
  const frame=el('div',null,rect?'book-crop':'book-page');frame.setAttribute('role','img');frame.setAttribute('aria-label','مِنْ صَفْحَةِ '+digits(page)+' فِي كِتَابِ الْقِرَاءَةِ');
  const r=rect||[0,0,BOOK.width,BOOK.height],w=r[2]-r[0],h=r[3]-r[1];frame.style.aspectRatio=w+'/'+h;if(rect)frame.style.maxWidth=Math.round(Math.min(520,Math.max(200,300*w/h)))+'px';
  const img=el('img');img.alt='';img.draggable=false;img.style.width=(BOOK.width/w*100)+'%';img.style.height=(BOOK.height/h*100)+'%';img.style.left=(-r[0]/w*100)+'%';img.style.top=(-r[1]/h*100)+'%';
  const loading=el('p','جَارٍ تَحْمِيلُ صُوَرِ الْكِتَابِ…','book-loading');frame.append(loading);
  function show(){const src=window.BOOK_IMAGES?.[page];if(src){img.onload=()=>{loading.hidden=true;};img.onerror=()=>{loading.hidden=false;loading.textContent='تَعَذَّرَ عَرْضُ الصُّورَةِ.';};img.src=src;frame.append(img);}}
  if(window.BOOK_IMAGES?.[page])show();else loadBookImages(page).then(show).catch(()=>{loading.textContent='تَعَذَّرَ تَحْمِيلُ الصُّوَرِ.';frame.append(button('إِعَادَةُ الْمُحَاوَلَةِ',()=>{loadBookImages(page).then(show).catch(()=>{});}));});return frame;
 }
 function bookCatalog(){
  title('اللُّغَةُ الْعَرَبِيَّةُ','كِتَابُ الْقِرَاءَةِ • أَحْمَدُ سَامِي دَرْوِيش');
  const welcome=el('div',null,'book-intro');add(welcome,el('strong',host()?'نَعْرِضُ الدَّرْسَ، ثُمَّ تَقْرَأُ رُقَيَّة':'نَقْرَأُ مَعَ إِيسُو 💜'),el('p',host()?'اِخْتَرْ صَفْحَةً. فِي الْأَسْئِلَةِ أَنْتَ مَنْ يُقَيِّمُ الْقِرَاءَةَ.':'إِيسُو يَخْتَارُ الدَّرْسَ وَيَسْتَمِعُ لِقِرَاءَتِكِ.'));root.append(welcome);
  BOOK.sections.forEach((s,i)=>{const group=el('details',null,'book-section');group.open=i===0;group.append(el('summary',digits(i+1)+' · '+s.title));const list=el('div',null,'book-lessons');BOOK.lessons.filter(l=>l.section===s.id).forEach(l=>{const b=button('',()=>bookOpen(l),'book-lesson');b.disabled=!host();add(b,el('span','ص '+digits(l.page),'book-page-number'),el('strong',l.title),el('small',l.guide?'شَرْحُ الْكِتَابِ':digits(l.cards.length)+' بِطَاقَةَ قِرَاءَةٍ'));list.append(b);});group.append(list);root.append(group);});
  const refs=el('details',null,'book-section');refs.append(el('summary','غِلَافُ الْكِتَابِ وَالْمُقَدِّمَةُ وَالْفِهْرِسُ'));[1,2,3,4,103,104].forEach(page=>{const b=button('صَفْحَةُ '+digits(page),()=>bookControl({phase:'subject',subject:'arabic',index:page,readingStep:3}),'secondary');b.disabled=!host();refs.append(b);});root.append(refs);
 }
 function bookFeedback(value){if(!host()||room.control.phase!=='quiz'||room.control.readingStep===1)return;return bookControl({readingStep:value});}
 function bookLesson(){
  const c=room.control,{l}=lesson();if(!l?.bookExact){bookCatalog();return;}const testing=c.phase==='quiz',done=c.phase==='end';
  const nav=el('div',null,'book-top-nav');const back=button('↩ الدُّرُوسُ',schoolHome,'secondary');back.disabled=!host();nav.append(back);nav.append(el('small','صَفْحَةُ '+digits(l.page)+' • '+l.title));root.append(nav);
  if(done){title('أَحْسَنْتِ يَا رُقَيَّة! 🌟','أَنْهَيْنَا قِرَاءَةَ هَذِهِ الصَّفْحَةِ.');root.append(el('p','قَرَأْنَا '+digits(l.cards.length)+' بِطَاقَةً مَعًا.','center'));if(host()){root.append(button('نُرَاجِعُ الدَّرْسَ',()=>bookOpen(l),'primary'));const nextLesson=BOOK.lessons[BOOK.lessons.indexOf(l)+1];if(nextLesson)root.append(button('الصَّفْحَةُ التَّالِيَةُ',()=>bookOpen(nextLesson),'secondary'));}return;}
  const at=testing?c.round:c.index,card=l.cards[at];if(!l.guide&&!card){title('اِخْتَرْ صَفْحَةً لِنَبْدَأَ.');return;}
  title(l.guide?'نَسْتَعْرِضُ شَرْحَ الْكِتَابِ':testing?'اِقْرَئِي يَا رُقَيَّة':'نَقْرَأُ مَعًا',l.guide?'':(testing?'السُّؤَالُ ':'الْبِطَاقَةُ ')+digits(at+1)+' مِنْ '+digits(l.cards.length));
  const full=l.guide||(!testing&&c.readingStep===3);const panel=el('section',null,'book-stage'),pan=el('div',null,'book-pan'),picture=bookPicture(l.page,full?null:testing?(card.quizRect||card.rect):card.rect);pan.append(picture);panel.append(pan);root.append(panel);let zoomed=false;const originalMax=picture.style.maxWidth;const zoom=button('🔍 تَكْبِيرُ الْعَرْضِ',()=>{zoomed=!zoomed;picture.style.minWidth=zoomed?'700px':'0';picture.style.maxWidth=zoomed?'none':originalMax;zoom.textContent=zoomed?'تَصْغِيرُ الْعَرْضِ':'🔍 تَكْبِيرُ الْعَرْضِ';if(zoomed)pan.scrollLeft=pan.scrollWidth;},'book-zoom');root.append(zoom);
  if(l.guide){if(host()){const nextLesson=BOOK.lessons[BOOK.lessons.indexOf(l)+1];if(nextLesson)root.append(button('الصَّفْحَةُ التَّالِيَةُ',()=>bookOpen(nextLesson),'primary'));}return;}
  if(testing){
   const feedback=el('div',null,'book-feedback');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');
   const value=c.readingStep===1?1:c.readingStep===2?2:0;
   if(value){const message=value===1?'أَحْسَنْتِ يَا رُقَيَّة، الْإِجَابَةُ صَحِيحَةٌ.':'الْإِجَابَةُ لَيْسَتْ صَحِيحَةً، حَاوِلِي مَرَّةً أُخْرَى يَا رُقَيَّة.';feedback.className+=' '+(value===1?'is-correct':'is-retry');feedback.textContent=message;if(bookFeedbackRev!==c.rev){bookFeedbackRev=c.rev;playEffect(value===1?'correct':'wrong');speak(message);}}
   else feedback.textContent=host()?'اِسْتَمِعْ لِقِرَاءَتِهَا، ثُمَّ اخْتَرْ.':'إِيسُو يَسْتَمِعُ إِلَيْكِ 💜';root.append(feedback);
   if(host()){const row=el('div',null,'book-assessment');if(value!==1){add(row,button('✓ صَحِيحٌ',()=>bookFeedback(1),'book-correct'),button('↻ خَطَأٌ — حَاوِلِي مَرَّةً أُخْرَى',()=>bookFeedback(2),'book-retry'));}else row.append(button(at+1<l.cards.length?'السُّؤَالُ التَّالِي':'نُنْهِي الْقِرَاءَةَ',()=>bookControl(at+1<l.cards.length?{round:at+1,readingStep:0}:{phase:'end',readingStep:0}),'primary'));root.append(row);root.append(button('رُجُوعٌ إِلَى الشَّرْحِ',()=>bookControl({phase:'learn',index:at,readingStep:0}),'secondary'));}
  }else if(host()){
   const nav=el('div',null,'book-card-nav');const previous=button('السَّابِقُ',()=>bookControl({index:at-1,readingStep:0}),'secondary');previous.disabled=at===0;nav.append(previous);if(at+1<l.cards.length)nav.append(button('التَّالِي',()=>bookControl({index:at+1,readingStep:0}),'primary'));else nav.append(button('نَبْدَأُ أَسْئِلَةَ الْقِرَاءَةِ',()=>bookControl({phase:'quiz',round:0,readingStep:0}),'primary'));root.append(nav);
   const extra=el('div',null,'book-extra');add(extra,button(full?'الْبِطَاقَةُ الْمُكَبَّرَةُ':'الصَّفْحَةُ الْأَصْلِيَّةُ',()=>bookControl({readingStep:full?0:3}),'secondary'),button('أَسْئِلَةُ هَذِهِ الصَّفْحَةِ',()=>bookControl({phase:'quiz',round:0,readingStep:0}),'secondary'));root.append(extra);
  }else root.append(el('p','إِيسُو يُقَلِّبُ الْبِطَاقَاتِ.','center'));
 }
 function render(){if(!active||!room?.control)return;const c=room.control,stamp=c.rev+':'+c.phase;if(stamp===view){updateSession();return;}view=stamp;closeBoard();pending={};stroke=null;shell();renderedPhase=c.phase;
  if(c.phase==='waiting'){title(host()?'غُرْفَتُنَا جَاهِزَةٌ 💌':'دَخَلْتِ مَعَ إِيسُو 💜',host()?'أَرْسِلِ الدَّعْوَةَ لِرُقَيَّة.':'نَنْتَظِرُ اتِّصَالَ إِيسُو.');if(host()){root.append(button('💌 أَرْسِلْ رَابِطَ الدَّعْوَةِ',shareInvite,'primary'));const badge=el('strong',null,'room-code');badge.textContent=id;root.append(badge);}}
  else if(c.phase==='subject'&&c.readingStep===3&&[1,2,3,4,103,104].includes(c.index)){const b=button('↩ الدُّرُوسُ',schoolHome);b.disabled=!host();root.append(b);root.append(bookPicture(c.index));}
  else if(['learn','quiz','end'].includes(c.phase)&&lesson().l?.bookExact)bookLesson();else bookCatalog();updateSession();
 }
 function start(phase){const {l}=lesson();control({phase,round:0,order:shuffle(l.cards.map((_,i)=>i)),guestCorrect:0,guestDone:0});}
 function headerTurn(t){const c=room.control,{l}=lesson();title('دَوْرُ '+names[t.role], 'الدَّوْرُ '+(c.round+1)+' مِنْ '+tasks().length);const p=el('p',mine(t.role)?(t.role==='guest'?'🌟 هَيَّا يَا رُقَيَّة، هَذَا دَوْرُكِ!':'🌟 هَيَّا يَا إِيسُو، هَذَا دَوْرُكَ!'):'👀 نُشَجِّعُ '+names[t.role]+' وَنَنْتَظِرُ دَوْرَنَا.','turn-banner');root.append(p);}
 function oral(){const t=task(),card=lesson().l.cards[t.card];headerTurn(t);const p=el('section',null,'panel');add(p,el('h2','🎭 نُمَثِّلُ الْمَوْقِفَ'),el('p',card.activity),learningExtras(card),button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 أَسْتَمِعُ',()=>host()?sharedAudio():speak(card.word,'en'),'secondary'),el('p','نَقُولُ الْجُمْلَةَ، ثُمَّ نُغَيِّرُ كَلِمَةً وَنُجَرِّبُ مَرَّةً أُخْرَى. إِيسُو يُلَاحِظُ الْفَهْمَ وَالنُّطْقَ.','muted'));root.append(p);if(!response()&&mine(t.role))root.append(button('قُلْتُ الْجُمْلَةَ ✅',async()=>{if(busy)return;busy=true;if(await write('responses/r'+room.control.rev,{role:t.role,value:'spoken'})){view='';render();}busy=false;},'primary'));if(response()){root.append(el('p','شُكْرًا لِلْمُحَاوَلَةِ 💜'));if(host())root.append(button('الدَّوْرُ التَّالِي',next,'primary'));}}
 function wordBuilder(){const t=task(),card=lesson().l.cards[t.card],rev=room.control.rev,key='r'+rev,r=response();headerTurn(t);const p=el('section',null,'panel center');add(p,card.reading?el('div','🧩','reading-puzzle'):cardVisual(card),el('h2','🧩 نُرَكِّبُ الْكَلِمَةَ'),el('p','اِسْمَعِي، ثُمَّ اضْغَطِي عَلَى الْحُرُوفِ بِالتَّرْتِيبِ أَوِ اسْحَبِيهَا إِلَى الْخَانَاتِ.'),button('🔊 الْكَلِمَةُ',()=>speak(card.word),'secondary'));root.append(p);
  const raw=room.arrangements?.[key]?.tiles,chosen=Array.from({length:card.tiles.length},(_,i)=>Number.isInteger(raw?.[i])?raw[i]:-1);
  const editable=mine(t.role)&&!r&&online;
  async function change(index,tile){if(!editable||busy||room.control.rev!==rev)return;const next=[...chosen];if(tile>=0){const old=next.indexOf(tile);if(old>=0)next[old]=-1;}next[index]=tile;busy=true;const ok=await write('arrangements/'+key,{role:t.role,tiles:next});busy=false;if(ok){view='';render();}}
  const slots=el('div',null,'word-slots');slots.dir='rtl';chosen.forEach((tile,i)=>{const b=button(tile>=0?card.tiles[tile]:'…',()=>change(i,-1),'word-slot');b.disabled=!editable;b.dataset.slot=String(i);b.setAttribute('aria-label','الْخَانَةُ '+(i+1));b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();const n=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(n)&&n>=0&&n<card.tiles.length)change(i,n);};slots.append(b);});p.append(slots);
  const bank=el('div',null,'letter-bank');bank.dir='rtl';const order=card.tiles.map((_,i)=>i).reverse();order.forEach(i=>{let suppressClick=false;const b=button(card.tiles[i],()=>{if(suppressClick){suppressClick=false;return;}const empty=chosen.indexOf(-1);if(empty>=0)change(empty,i);},'letter-tile');b.disabled=!editable||chosen.includes(i);b.draggable=!b.disabled;b.setAttribute('aria-label','حَرْف '+card.tiles[i]);b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));let start=null,moved=false;b.onpointerdown=e=>{if(b.disabled)return;start=[e.clientX,e.clientY];moved=false;if(b.setPointerCapture)b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(start&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>12)moved=true;};b.onpointerup=e=>{if(!start)return;start=null;if(moved){const target=document.elementFromPoint?.(e.clientX,e.clientY)?.closest?.('.word-slot');if(target)change(Number(target.dataset.slot),i);suppressClick=true;}};bank.append(b);});p.append(bank);
  const formed=chosen.map(i=>i>=0?card.tiles[i]:'ـ').join('');p.append(el('div',formed,'assembled-word'));
  if(editable){const submit=button('تَحَقَّقْ مِنَ الْكَلِمَةِ',async()=>{if(busy||chosen.includes(-1)||room.control.rev!==rev)return;busy=true;const ok=await write('responses/'+key,{role:t.role,value:formed});busy=false;if(ok){view='';render();}},'primary');submit.disabled=chosen.includes(-1);p.append(submit);}
  if(r){const correct=r.value===card.answer;add(p,el('p',correct?'أَحْسَنْتَ! نَتَعَلَّمُ مَعًا 🌟':'نُرَاجِعُ الْكَلِمَةَ مَعًا 💜','feedback'),el('p',card.answer,'assembled-word'));if(lastFeedbackRev!==rev){lastFeedbackRev=rev;playEffect(correct?'correct':'wrong');speak((correct?(t.role==='guest'?'أَحْسَنْتِ يَا رُقَيَّة. ':'أَحْسَنْتَ يَا إِيسُو. '):'نُرَاجِعُ مَعًا. ')+card.answer);}if(host())root.append(button('التَّالِي',next,'primary'));}else if(!mine(t.role))p.append(el('p','نُشَاهِدُ الْحُرُوفَ وَهِيَ تُرَتَّبُ.','muted'));
 }

 function quiz(){const t=task(),{l}=lesson(),card=l.cards[t.card],opts=DuoPlan.options(card,room.control.round);headerTurn(t);const p=el('div',null,'panel center');if(card.sceneText){p.append(el('p',card.sceneText,'story-text'));p.append(button('🔊 نَسْمَعُ الْمَشْهَدَ',()=>speak(card.sceneText),'secondary'));}p.append(el('h2',card.q,(l.id==='add'||card.visual?.type==='operation'||l.id==='math_symbols')?'equation':''));if(card.reading?.type==='fade'){p.append(ReadingView.render(card,3));p.append(el('p',card.detail.replace(card.word,ReadingView.marks(card.word,3)),'reading-context'));}else if(card.visual||['compare','shapes','colors'].includes(l.id))p.append(cardVisual(card));if(l.id.startsWith('num'))p.append(el('div',card.detail,'count'));p.append(button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 السُّؤَالُ وَالْإِجَابَاتُ',()=>host()?sharedAudio():speak(questionSpeech(card,opts),card.lang),'secondary'));root.append(p);const choices=el('div',null,'choices');const r=response();opts.forEach((o,i)=>{const wrap=el('div',null,'answer-card');const b=button('',async()=>{if(busy||response()||!mine(t.role))return;busy=true;const ok=await write('responses/r'+room.control.rev,{role:t.role,value:o});busy=false;if(ok){playEffect(o===card.answer?'correct':'wrong');view='';render();}},'choice');add(b,el('span',i+1,'answer-number'),el('span',optionPicture(o),'answer-picture'),el('span',o,'answer-label'));b.disabled=!mine(t.role)||!!r;if(r&&o===card.answer)b.classList.add('correct');if(r&&r.value===o&&o!==card.answer)b.classList.add('wrong');add(wrap,b,button('🔊 '+(i+1),()=>speak(optionSpeech(o,i,card.lang),card.lang),'listen-choice'));choices.append(wrap);});root.append(choices);if(r){if(lastFeedbackRev!==room.control.rev){lastFeedbackRev=room.control.rev;if(role!==r.role||local)playEffect(r.value===card.answer?'correct':'wrong');if(card.lang==='en'){speakSequence([{text:r.value===card.answer?(t.role==='guest'?'أَحْسَنْتِ يَا رُقَيَّة':'أَحْسَنْتَ يَا إِيسُو'):'نُرَاجِعُ مَعًا',lang:'ar'},{text:card.answer,lang:'en'}]);}else if(r.value===card.answer)speak((t.role==='guest'?'أَحْسَنْتِ يَا رُقَيَّة':'أَحْسَنْتَ يَا إِيسُو')+'، الْإِجَابَةُ '+speechText(card.answer,card.lang),'ar');else speak('نُرَاجِعُ مَعًا. الْإِجَابَةُ الصَّحِيحَةُ '+speechText(card.answer,card.lang),'ar');}root.append(el('p',r.value===card.answer?(t.role==='guest'?'أَحْسَنْتِ يَا ':'أَحْسَنْتَ يَا ')+names[t.role]+'! الْإِجَابَةُ: '+card.answer+' 🌟':'نَتَعَلَّمُ مَعًا. الْإِجَابَةُ الصَّحِيحَةُ: '+card.answer,'feedback'));if(host())root.append(button('التَّالِي',next,'primary'));else root.append(el('p','نَنْتَظِرُ إِيسُو لِنُكْمِلَ.'));}}
 async function next(){const c=room.control,t=task(),{l}=lesson(),r=response();if(!r)return;const right=c.phase==='quiz'&&['choice','build'].includes(t.kind)&&r.value===l.cards[t.card].answer;const expected=l.cards.filter(x=>!['draw','dictation'].includes(x.practice)).length;const done=(c.guestDone||0)+(t.role==='guest'&&['choice','build'].includes(t.kind)?1:0),correct=(c.guestCorrect||0)+(t.role==='guest'&&right?1:0);const progress={...(c.progress||{})};if(c.phase==='quiz'&&c.round+1===tasks().length&&expected>0&&done===expected){const stars=correct===expected?3:correct>=Math.ceil(expected/2)?2:1;progress[l.id]=Math.max(progress[l.id]||0,stars);}await control({progress,round:c.round+1,guestDone:done,guestCorrect:correct,phase:c.round+1===tasks().length?'end':c.phase,finished:c.phase});}
 function finishDuo(){const {l}=lesson(),c=room.control,expected=l.cards.filter(x=>!['draw','dictation'].includes(x.practice)).length;title('أَحْسَنْتُمَا! 🎉','تَدَرَّبَ كُلٌّ مِنْكُمَا عَلَى جَمِيعِ الْبِطَاقَاتِ.');if(c.finished==='quiz'&&expected>0&&c.guestDone===expected){const stars=c.guestCorrect===expected?3:c.guestCorrect>=Math.ceil(expected/2)?2:1;if(local||role==='guest'){state.best[l.id]=Math.max(state.best[l.id]||0,stars);save();}add(root,el('p','نُجُومُ رُقَيَّة: '+'⭐'.repeat(stars),'stars'),el('p','الْإِجَابَاتُ الصَّحِيحَةُ لِرُقَيَّة: '+c.guestCorrect+' مِنْ '+expected));}else root.append(el('p','رَاجِعَا الْكِتَابَةَ مَعًا؛ لَا يُقَيِّمُ التَّطْبِيقُ خَطَّ الْيَدِ تِلْقَائِيًّا.'));if(l.guided){root.append(ratingPanel(l.id));root.append(courseButton('نَرْجِعُ إِلَى خُطَّةِ الْيَوْمِ',()=>control({phase:'week'})));}if(host())add(root,button('✏️ نَكْتُبُ مَعًا',()=>start('write'),'primary'),button('🎯 نُجِيبُ عَنِ الْأَسْئِلَةِ',()=>start('quiz'),'secondary'),button('دَرْسٌ آخَرُ',()=>control({phase:'pick'})));}
 function board(){const t=task(),{s,l}=lesson(),card=l.cards[t.card],c=room.control;headerTurn(t);if(host())root.append(button('↩ الرُّجُوعُ إِلَى الدُّرُوسِ',()=>control({phase:'subject',subject:s.id}),'secondary board-back'));const target=t.target||DuoPlan.target(s,card);if(card.traceLetter)root.append(el('p',['١: نَتَتَبَّعُ الْمَسَارَ وَالسَّهْمَ.','٢: نَنْسَخُ النَّمُوذَجَ الْخَفِيفَ.','٣: نَكْتُبُ وَحْدَنَا.'][t.position||0],'turn-banner'));add(root,el('p',['arabic','english','math'].includes(s.id)?'نَكْتُبُ النَّمُوذَجَ عَلَى السَّطْرِ.':'نَرْسُمُ مَا يُعَبِّرُ عَنِ الْبِطَاقَةِ، وَنَتَحَدَّثُ عَنْهَا.','center'),el('h2',card.practice==='dictation'&&!response()?'🔊 اِسْمَعِي ثُمَّ اكْتُبِي':target,'writing-target'),button(host()?'🔊 نَسْتَمِعُ مَعًا':'🔊 أَسْتَمِعُ',()=>host()?sharedAudio():speak(target,card.lang),'secondary'));if(card.steps)root.append(learningExtras(card));const canvas=el('canvas',null,'trace shared-board');canvas.width=900;canvas.height=560;canvas.setAttribute('aria-label','سبورة مشتركة للكتابة');root.append(canvas);const ctx=canvas.getContext('2d'),path='boards/r'+c.rev;pendingPath=path;pending={};canvasStrokes=mine(t.role)?{...(room.boards?.['r'+c.rev]||{})}:{};stroke=null;
  function redraw(){ctx.clearRect(0,0,900,560);ctx.fillStyle='#fffdf9';ctx.fillRect(0,0,900,560);const ys=s.id==='art'?[]:s.id==='english'?[160,260,360,440]:[230,410];ys.forEach((y,i)=>{ctx.strokeStyle=i===2?'#9d83cb':'#d5cbdf';ctx.lineWidth=2;ctx.setLineDash(s.id==='english'&&i===1?[12,9]:[]);ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(870,y);ctx.stroke();});ctx.setLineDash([]);if(card.traceLetter){paintTrace(ctx,card.traceLetter,t.position||0);}else if(card.practice==='trace'){ctx.fillStyle='#e4dcec';ctx.font='140px sans-serif';ctx.textAlign='center';ctx.fillText(target,450,230);}const strokes={...(room.boards?.['r'+c.rev]||{}),...canvasStrokes,...pending};Object.values(strokes).forEach(st=>{if(!st||!Array.isArray(st.points)||!/^#[a-f0-9]{6}$/i.test(st.color))return;ctx.strokeStyle=st.color;ctx.fillStyle=st.color;ctx.lineWidth=7;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();st.points.forEach((p,i)=>{if(i===0)ctx.moveTo(p[0]*900,p[1]*560);else ctx.lineTo(p[0]*900,p[1]*560);});ctx.stroke();if(st.points.length===1){ctx.beginPath();ctx.arc(st.points[0][0]*900,st.points[0][1]*560,3.5,0,Math.PI*2);ctx.fill();}});}
  drawRefresh=redraw;listenBoard(c.rev);
  const pos=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
  canvas.onpointerdown=e=>{if(!mine(t.role)||response()||(!local&&!online)||Object.keys(canvasStrokes).length>=150)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);stroke='s'+Object.keys(canvasStrokes).length;canvasStrokes[stroke]={role:t.role,color:ink,points:[pos(e)]};pending[stroke]=canvasStrokes[stroke];redraw();scheduleFlush();};
  canvas.onpointermove=e=>{if(!stroke||room.flags?.paused||!online)return;e.preventDefault();const st=canvasStrokes[stroke];if(st.points.length>=300)return;st.points.push(pos(e));pending[stroke]=st;redraw();scheduleFlush();};canvas.onpointerup=canvas.onpointercancel=()=>{stroke=null;flush();};
  const palette=el('div',null,'palette');['#7753c7','#277fc5','#369a78','#eb6487','#30384d'].forEach(color=>{const b=button('',()=>ink=color,'swatch');b.style.background=color;b.setAttribute('aria-label',color);palette.append(b);});root.append(palette);if(mine(t.role)&&!response()){add(root,button('تَرَاجُعٌ عَنْ آخِرِ خَطٍّ',async()=>{if(flushing||stroke||Object.keys(pending).length)return;const keys=Object.keys(canvasStrokes);if(!keys.length)return;const last=keys.at(-1);if(await write(path+'/'+last,null)){delete canvasStrokes[last];redraw();}},'secondary'),button('انْتَهَيْتُ ✅',async()=>{if(busy)return;busy=true;await flush();if(flushing||Object.keys(pending).length){status('انْتَظِرْ حَفْظَ الْكِتَابَةِ، ثُمَّ اضْغَطْ مَرَّةً أُخْرَى.');busy=false;return;}if(await write('responses/r'+c.rev,{role:t.role,value:'done'})){playEffect('correct');view='';render();}busy=false;},'primary'));}if(response()){root.append(el('p','نُرَاجِعُ الْكِتَابَةَ مَعًا 💜'));if(host())root.append(button('الدَّوْرُ التَّالِي',next,'primary'));}redraw();
 }
 function scheduleFlush(){if(flushTimer)return;flushTimer=setTimeout(()=>{flushTimer=null;flush();},75);}
 async function listenBoard(rev){if(local||!window.EventSource||streamRev===rev)return;if(boardStream)boardStream.close();streamRev=rev;const e=epoch;try{const t=await token();if(e!==epoch||room.control.rev!==rev)return;const url=cfg.databaseURL+'/studyRoomsV3/'+id+'/boards/r'+rev+'.json?auth='+encodeURIComponent(t);const source=new EventSource(url);boardStream=source;const handle=event=>{if(e!==epoch||room.control.rev!==rev)return;try{const msg=JSON.parse(event.data),parts=msg.path.split('/').filter(Boolean),key='r'+rev;let board=parts.length?{...(room.boards?.[key]||{})}:{};if(!parts.length)board=event.type==='put'?msg.data||{}:{...board,...msg.data};else if(parts.length===1){if(msg.data===null)delete board[parts[0]];else board[parts[0]]=event.type==='patch'?{...board[parts[0]],...msg.data}:msg.data;}else{const st={...(board[parts[0]]||{})};st[parts[1]]=msg.data;board[parts[0]]=st;}room.boards={...(room.boards||{}),[key]:board};if(drawRefresh)drawRefresh();}catch(ignore){}};source.addEventListener('put',handle);source.addEventListener('patch',handle);source.addEventListener('auth_revoked',()=>{source.close();boardStream=null;streamRev=-1;});source.addEventListener('cancel',()=>{source.close();boardStream=null;streamRev=-1;});}catch(ignore){streamRev=-1;}}
 function flush(){if(flushJob)return flushJob;flushJob=sendStrokes().finally(()=>{flushJob=null;});return flushJob;}
 async function sendStrokes(){if(flushing||!Object.keys(pending).length||!active)return;flushing=true;const batch=JSON.parse(JSON.stringify(pending)),path=pendingPath,e=epoch;pending={};try{if(local){Object.entries(batch).forEach(([k,v])=>putLocal(path+'/'+k,v));}else{await db(path,'PATCH',batch);if(e!==epoch)return;Object.entries(batch).forEach(([k,v])=>putLocal(path+'/'+k,v));} }catch(error){if(active&&e===epoch&&path===pendingPath)pending={...batch,...pending};status('لَمْ تُحْفَظْ بَعْضُ الْخُطُوطِ. اِنْتَظِرْ عَوْدَةَ الِاتِّصَالِ.');}finally{flushing=false;if(active&&e===epoch&&Object.keys(pending).length)scheduleFlush();}}
 if(document.addEventListener)document.addEventListener('visibilitychange',()=>document.visibilityState==='hidden'?suspend():reconnect());
 if(window.addEventListener)for(const event of ['pageshow','online','focus'])window.addEventListener(event,()=>reconnect());
 return {reconnect,suspend,lobby,leave,home:schoolHome,back,acceptInvite,extractInvite,isActive:()=>active,configValid};
})();
home=()=>Duo.home();
document.getElementById('home').onclick=home;
window.appBack=()=>Duo.back();
window.schoolInvite=code=>Duo.acceptInvite(code);
const invite=window.location?Duo.extractInvite(window.location.href):'';
if(invite)Duo.acceptInvite(invite);else Duo.lobby();
if(window.Android?.getInvite){const incoming=Android.getInvite();if(incoming)Duo.acceptInvite(incoming);}
window.addEventListener?.('hashchange',()=>Duo.acceptInvite(window.location.href));

window.schoolResume=()=>Duo.reconnect();
window.schoolSuspend=()=>Duo.suspend();
